function V(wrd) {print wrd " V Abl Pl"
print wrd " V Abl Sg PxSg1"
print wrd " V Ade Pl"
print wrd " V All Pl"
print wrd " V All Sg"
print wrd " V Cond Act Pl1"
print wrd " V Cond Act Pl2"
print wrd " V Ill Sg PxSg2"
print wrd " V N Abl Pl"
print wrd " V N All Sg"
print wrd " V Neg Pl3"
print wrd " V N Gen Pl"
print wrd " V N Ins Pl"
print wrd " V N Nom Sg Px3"
print wrd " V N Par Pl Px3"
print wrd " V N Par Sg PxSg1"
print wrd " V N Tra Sg"
print wrd " V Par Sg Px3"
print wrd " V Gen Pl"
print wrd " V N Ine Pl"
print wrd " V N Ine Sg"
print wrd " V N Nom Sg PxSg1"
print wrd " V Ade Sg Px3"
print wrd " V Cond Pass Pe4"
print wrd " V Inf1 Act Tra Sg PxSg2"
print wrd " V N Gen Sg Px3"
print wrd " V N Gen Sg PxPl1"
print wrd " V N Ill Sg"
print wrd " V N Nom Pl Px3"
print wrd " V N Nom Pl PxPl1"
print wrd " V N Nom Sg PxPl1"
print wrd " V N Par Sg PxSg2"
print wrd " V Gen Sg PxSg2"
print wrd " V Inf1 Act Tra Sg PxPl1"
print wrd " V Inf1 Act Tra Sg PxSg1"
print wrd " V Inf3 Abe Px3"
print wrd " V Nom Pl PxSg2"
print wrd " V Nom Sg PxSg2"
print wrd " V N Tra Pl"
print wrd " V Pot Pass Pe4"
print wrd " V Pst Act Pl2"
print wrd " V Ade Sg"
print wrd " V Inf3 Pass Ins"
print wrd " V N Gen Sg PxSg1"
print wrd " V N Nom Pl PxSg1"
print wrd " V Ins Pl"
print wrd " V Inf2 Act Ine Sg PxSg1"
print wrd " V Ela Pl"
print wrd " V Ill Pl"
print wrd " V N Ela Pl"
print wrd " V Impv Pass Pe4 ConNeg"
print wrd " V Abl Sg"
print wrd " V N Ill Pl"
print wrd " V Inf2 Act Ine Sg Px3"
print wrd " V Impv Act Sg3"
print wrd " V Par Pl"
print wrd " V Nom Pl"
print wrd " V Par Sg"
print wrd " V Inf1 Act Tra Sg Px3"
print wrd " V Tra Sg"
print wrd " V Pot Pass Pe4 ConNeg"
print wrd " V Ela Sg"
print wrd " V Impv Pass Pe4"
print wrd " V N Par Pl"
print wrd " V Gen Sg"
print wrd " V Pst Act Pl1"
print wrd " V Ine Sg"
print wrd " V Ine Pl"
print wrd " V N Ela Sg"
print wrd " V N Nom Pl"
print wrd " V Neg Sg1"
print wrd " V Ill Sg"
print wrd " V N Par Sg Px3"
print wrd " V Inf2 Act Ine Sg"
print wrd " V Inf2 Pass Ine"
print wrd " V Inf2 Pass Ins"
print wrd " V Cond Pass Pe4 ConNeg"
print wrd " V Cond Act Sg2"
print wrd " V Nom Sg"
print wrd " V Pst Pass Pe4"
print wrd " V Inf3 Ela"
print wrd " V Prs Act Pl2"
print wrd " V N Gen Sg"
print wrd " V Inf3 Ade"
print wrd " V Inf3 Ine"
print wrd " V N Nom Sg"
print wrd " V Prs Pass Pe4"
print wrd " V N Par Sg"
print wrd " V Pot Act Sg2"
print wrd " V Impv ConNeg"
print wrd " V Pst Act Sg2"
print wrd " V Cond Act Sg3"
print wrd " V Inf3 Abe"
print wrd " V Prs Act Pl1"
print wrd " V Inf3 Man"
print wrd " V Pst Act Pl3"
print wrd " V Inf3 Ill"
print wrd " V Cond Act Sg1"
print wrd " V Pst Pass ConNeg"
print wrd " V Pot Act ConNeg"
print wrd " V Pot Act Sg1"
print wrd " V Pst Act ConNeg"
print wrd " V Prs Act Sg2"
print wrd " V Neg Sg2"
print wrd " V Inf2 Act Ins"
print wrd " V Prs Act Pl3"
print wrd " V Prs Pass ConNeg"
print wrd " V Cond Act ConNeg"
print wrd " V Pst Act Sg3"
print wrd " V Pst Act Sg1"
print wrd " V Prs Act Sg1"
print wrd " V Prs Act Sg3"
print wrd " V Inf1 Lat"
print wrd " V Prs Act ConNeg"
print wrd " V Impv Act Sg2"
}
